# Generated by Django 4.2.1 on 2023-06-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('Emp_Name', models.CharField(max_length=80)),
                ('Emp_Id', models.CharField(primary_key=True, serialize=False)),
                ('Emp_Role', models.CharField(max_length=30)),
            ],
        ),
    ]
