# Generated by Django 4.2.1 on 2023-06-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='Emp_Id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
