# Generated by Django 4.2.1 on 2023-05-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomdetails',
            old_name=' 93E 100kVA INT O/P TRX,Al,O/S',
            new_name='801032569',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name=' 93E 100kva Int TRX-Cu O/S',
            new_name='801032694',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name=' 93E 160/200 IB BF',
            new_name='801033057S - WR 93E, 80 kVA, MBS, IT42 TRX MBS Datson',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name=' 93E 160/200Kva MBS-SF-O/S',
            new_name='Assembly/Sub_part',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name=' 93E 160KVA MBS INT CU TRX',
            new_name='Child_Part_No',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name=' 93E MBS, 3x400A',
            new_name='Clinching /Riveting',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name=' 93PM MBS, 3x500A',
            new_name='METAL_STAMP ',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name='200 kVA, MBS INT OUTPUT TRX, AL',
            new_name='Material',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name='80/100 MBS',
            new_name='POWDER_COATING',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name='93E , 200 KVA  I/P INTERNAL TRX, AL',
            new_name='Part_Name',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name='93E 100 KVA-INT AL TRX ',
            new_name='Qty_In_Drawing',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name='93E 100 MBS O/P INT CU TRX ',
            new_name='REV_NO',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name='93E 100Kva MBS-Int Trx-Al-O/S',
            new_name='Revion_No',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name='93E 120 KVA',
            new_name='Revision_Details',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name='93E 120 KVA MBS-O/P TRX AL',
            new_name='SL.NO',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name='93E 120 KVA NT AL TRX ',
            new_name='Source',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name='93E 120 KVA-MBS',
            new_name='Sub_Assy_part_No',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name='93E 120 kVA\xa0 O/P INT TRX, Al',
            new_name='Surface_Finish',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name='93E 120 kVA\xa0 O/P Internal Trx, Cu, K13,O/S',
            new_name='Tapping',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name='93E 120KVA MBS NBFOUTSOURCE P',
            new_name='Welding',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name='93E 120Kva MBS-Int Trx Al O/S',
            new_name='Wire_Rack/Non_Wire Rack_Parts',
        ),
        migrations.RenameField(
            model_name='bomdetails',
            old_name='93E 160 kVA\xa0 O/P INT TRX, Al',
            new_name='commodity',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E 160/200 KVA MBS-DF-O/S',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E 160/200 KVA MBS-DUAL FEED',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E 160/200KVA',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E 160kVA MBS,INT O/P TRX,Al,DF, O/S',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E 200 kVA  O/P INT TRX,Cu K13',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E 200kVA MBS,INT O/P AL TRX,DF O/S',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E 400KVA External MBS Panel',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E 80 kVA INT O/P TRX, Cu',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E 80/100KVA',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E 80/100KVA MBS NBF',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E 80KVA MBS,INT O/P TRX,CU FRLS O/S',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E 80Kva MBS-Int Trx-Al-O/S',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E100KVA MBS,INT O/P TRX,AL',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E120KVA MBS & BF I/P INT ALUMI TRX',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E120kVA,I/P INT Trx CuMBS O/S',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93E80kVA INT O/P TRX,Al,REGN O/S',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93PM STANDALONE MBS, 4x400A',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93PR MBS, 4x400A RO',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='93PR MBS, 4x500A RO',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='ELECTRICAL PANEL, 93E STANDALONE MBS',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Electrical Panel,500KVA EXT.MBS(3x1000A)',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='UPS 93E 100 kVA MBS,INT INPUT TRX AL,K13',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 0',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 1',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 2',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 3',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 52',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 53',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 54',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 55',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 56',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 57',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 58',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 59',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 60',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 61',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 62',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 63',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 64',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 65',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 66',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 67',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 68',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 69',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 70',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 71',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 72',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 73',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 74',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 75',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 76',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 77',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 78',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 79',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='Unnamed: 80',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='WIRD RK,93E 200 kVA\xa0 O/P INT TRX,Al,O/S',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='WIRED RACK, 93E 200KVA MBS I/P Al Trx, SF,O/S',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='WIRED RACK, 93E 200KVA MBS Int Trx- O/S',
        ),
        migrations.RemoveField(
            model_name='bomdetails',
            name='product Name',
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801023089',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032510',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032511',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032519',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032525',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032529',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032531',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032537',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032539',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032562',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032563',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032566',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032568',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032573',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032589',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032595',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032597',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032598',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032601',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032603',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032605S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032608',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032612S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032614S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032618',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032619',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032625',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032627S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032630S - WIRED RACK, 93E 160KVA MBS Int Trx-O/S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032632S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032638',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032641S - WIR RACK,93E 200KVA MBS INT O/P TRX- O/S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032651S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032652S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032656S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032658S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032662',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032665',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032697S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032719S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801032787S - WIRED RACK , 93E 500KVA Busbar Panel, O/S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801033001S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801033002',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801033006S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801033007',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801033008',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801033052S - WR, 93E 160KVA MBS, I/P Int Trx, K13, O/',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801033054S - WIR RCK,93E100kVA MBS INT TRX Cu,K13,O/S',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801033056S - WR ,93E 160KVA MBS,I/P Trx,W/t Trx MBS',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801033059S - WR,93E 160KVA MBS,I/P Trx,W/t Trx MBS OS',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='801212223',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='Blank_Wt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='Length',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='No.Of_Bends',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='Powder_Coating_Area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='Powder_Usage_in_Kgs',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='Quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='Thickness',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomdetails',
            name='Width',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bomdetails',
            name='Unnamed: 82',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bomdetails',
            name='Unnamed: 83',
            field=models.FloatField(),
        ),
    ]
