# Generated by Django 4.2.1 on 2023-06-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('planner_name', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('batch_control', models.IntegerField()),
                ('product_number', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('machines_available', models.IntegerField()),
            ],
        ),
    ]
