# Generated by Django 4.2.1 on 2023-06-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='batch_control',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='machines_available',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product_number',
            field=models.CharField(max_length=100),
        ),
    ]
