# Generated by Django 4.2.1 on 2023-06-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('part_no', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=50)),
                ('proposal_drawing', models.CharField(max_length=80)),
            ],
        ),
    ]
